### ISSUE TITLE
Rotate

### ISSUE THREAD

**Issue by crysan** [00ec454/pop#1]
Hi!

How the window behaves when calling in fragment and turning the device?

**Comment by 00ec454** [comment]
@crysan , if you have activity then you can directly invoke the Pop like

``` java
Pop.on(this).... //this is activity reference
```

if you have fragment then you can use like

``` java
Pop.on(this.getActivity()).... // this is fragment reference
```

Also it works fine with rotation.

**Comment by crysan** [comment]
Ty!

**Comment by 00ec454** [comment]
[here](https://github.com/00ec454/pop/blob/master/app/src/main/java/com/vistrav/poplib/MainActivity.java#L19-L56) is the code you can refer
